// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: encpb/encode_bunch.proto

#include "encpb/encode_bunch.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace algocomp {
class EncodeBunchDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<EncodeBunch>
      _instance;
} _EncodeBunch_default_instance_;
}  // namespace algocomp
namespace protobuf_encpb_2fencode_5fbunch_2eproto {
void InitDefaultsEncodeBunchImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_encpb_2fencode_5fdata_2eproto::InitDefaultsEncodeData();
  {
    void* ptr = &::algocomp::_EncodeBunch_default_instance_;
    new (ptr) ::algocomp::EncodeBunch();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::algocomp::EncodeBunch::InitAsDefaultInstance();
}

void InitDefaultsEncodeBunch() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsEncodeBunchImpl);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::algocomp::EncodeBunch, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::algocomp::EncodeBunch, encs_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::algocomp::EncodeBunch)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::algocomp::_EncodeBunch_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "encpb/encode_bunch.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\030encpb/encode_bunch.proto\022\010algocomp\032\027en"
      "cpb/encode_data.proto\"1\n\013EncodeBunch\022\"\n\004"
      "encs\030\001 \003(\0132\024.algocomp.EncodeDataB\036\n\010algo"
      "compB\rEncodeBunchPbP\001\370\001\001b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 152);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "encpb/encode_bunch.proto", &protobuf_RegisterTypes);
  ::protobuf_encpb_2fencode_5fdata_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_encpb_2fencode_5fbunch_2eproto
namespace algocomp {

// ===================================================================

void EncodeBunch::InitAsDefaultInstance() {
}
void EncodeBunch::clear_encs() {
  encs_.Clear();
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int EncodeBunch::kEncsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

EncodeBunch::EncodeBunch()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_encpb_2fencode_5fbunch_2eproto::InitDefaultsEncodeBunch();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:algocomp.EncodeBunch)
}
EncodeBunch::EncodeBunch(::google::protobuf::Arena* arena)
  : ::google::protobuf::Message(),
  _internal_metadata_(arena),
  encs_(arena) {
  ::protobuf_encpb_2fencode_5fbunch_2eproto::InitDefaultsEncodeBunch();
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:algocomp.EncodeBunch)
}
EncodeBunch::EncodeBunch(const EncodeBunch& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      encs_(from.encs_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:algocomp.EncodeBunch)
}

void EncodeBunch::SharedCtor() {
  _cached_size_ = 0;
}

EncodeBunch::~EncodeBunch() {
  // @@protoc_insertion_point(destructor:algocomp.EncodeBunch)
  SharedDtor();
}

void EncodeBunch::SharedDtor() {
  GOOGLE_DCHECK(GetArenaNoVirtual() == NULL);
}

void EncodeBunch::ArenaDtor(void* object) {
  EncodeBunch* _this = reinterpret_cast< EncodeBunch* >(object);
  (void)_this;
}
void EncodeBunch::RegisterArenaDtor(::google::protobuf::Arena* arena) {
}
void EncodeBunch::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* EncodeBunch::descriptor() {
  ::protobuf_encpb_2fencode_5fbunch_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_encpb_2fencode_5fbunch_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const EncodeBunch& EncodeBunch::default_instance() {
  ::protobuf_encpb_2fencode_5fbunch_2eproto::InitDefaultsEncodeBunch();
  return *internal_default_instance();
}

EncodeBunch* EncodeBunch::New(::google::protobuf::Arena* arena) const {
  return ::google::protobuf::Arena::CreateMessage<EncodeBunch>(arena);
}

void EncodeBunch::Clear() {
// @@protoc_insertion_point(message_clear_start:algocomp.EncodeBunch)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  encs_.Clear();
  _internal_metadata_.Clear();
}

bool EncodeBunch::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:algocomp.EncodeBunch)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .algocomp.EncodeData encs = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(input, add_encs()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:algocomp.EncodeBunch)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:algocomp.EncodeBunch)
  return false;
#undef DO_
}

void EncodeBunch::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:algocomp.EncodeBunch)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .algocomp.EncodeData encs = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->encs_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->encs(static_cast<int>(i)), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:algocomp.EncodeBunch)
}

::google::protobuf::uint8* EncodeBunch::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:algocomp.EncodeBunch)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .algocomp.EncodeData encs = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->encs_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->encs(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:algocomp.EncodeBunch)
  return target;
}

size_t EncodeBunch::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:algocomp.EncodeBunch)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .algocomp.EncodeData encs = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->encs_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->encs(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void EncodeBunch::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:algocomp.EncodeBunch)
  GOOGLE_DCHECK_NE(&from, this);
  const EncodeBunch* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const EncodeBunch>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:algocomp.EncodeBunch)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:algocomp.EncodeBunch)
    MergeFrom(*source);
  }
}

void EncodeBunch::MergeFrom(const EncodeBunch& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:algocomp.EncodeBunch)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  encs_.MergeFrom(from.encs_);
}

void EncodeBunch::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:algocomp.EncodeBunch)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void EncodeBunch::CopyFrom(const EncodeBunch& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:algocomp.EncodeBunch)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool EncodeBunch::IsInitialized() const {
  return true;
}

void EncodeBunch::Swap(EncodeBunch* other) {
  if (other == this) return;
  if (GetArenaNoVirtual() == other->GetArenaNoVirtual()) {
    InternalSwap(other);
  } else {
    EncodeBunch* temp = New(GetArenaNoVirtual());
    temp->MergeFrom(*other);
    other->CopyFrom(*this);
    InternalSwap(temp);
    if (GetArenaNoVirtual() == NULL) {
      delete temp;
    }
  }
}
void EncodeBunch::UnsafeArenaSwap(EncodeBunch* other) {
  if (other == this) return;
  GOOGLE_DCHECK(GetArenaNoVirtual() == other->GetArenaNoVirtual());
  InternalSwap(other);
}
void EncodeBunch::InternalSwap(EncodeBunch* other) {
  using std::swap;
  encs_.InternalSwap(&other->encs_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata EncodeBunch::GetMetadata() const {
  protobuf_encpb_2fencode_5fbunch_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_encpb_2fencode_5fbunch_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace algocomp

// @@protoc_insertion_point(global_scope)
