// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: attrpb/setcate_value.proto

#include "attrpb/setcate_value.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace algocomp {
class SetCateValue_ValsEntry_DoNotUseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SetCateValue_ValsEntry_DoNotUse>
      _instance;
} _SetCateValue_ValsEntry_DoNotUse_default_instance_;
class SetCateValueDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SetCateValue>
      _instance;
} _SetCateValue_default_instance_;
}  // namespace algocomp
namespace protobuf_attrpb_2fsetcate_5fvalue_2eproto {
void InitDefaultsSetCateValue_ValsEntry_DoNotUseImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::algocomp::_SetCateValue_ValsEntry_DoNotUse_default_instance_;
    new (ptr) ::algocomp::SetCateValue_ValsEntry_DoNotUse();
  }
  ::algocomp::SetCateValue_ValsEntry_DoNotUse::InitAsDefaultInstance();
}

void InitDefaultsSetCateValue_ValsEntry_DoNotUse() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsSetCateValue_ValsEntry_DoNotUseImpl);
}

void InitDefaultsSetCateValueImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_attrpb_2fsetcate_5fvalue_2eproto::InitDefaultsSetCateValue_ValsEntry_DoNotUse();
  {
    void* ptr = &::algocomp::_SetCateValue_default_instance_;
    new (ptr) ::algocomp::SetCateValue();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::algocomp::SetCateValue::InitAsDefaultInstance();
}

void InitDefaultsSetCateValue() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsSetCateValueImpl);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::algocomp::SetCateValue_ValsEntry_DoNotUse, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::algocomp::SetCateValue_ValsEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::algocomp::SetCateValue_ValsEntry_DoNotUse, key_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::algocomp::SetCateValue_ValsEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::algocomp::SetCateValue, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::algocomp::SetCateValue, vals_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, sizeof(::algocomp::SetCateValue_ValsEntry_DoNotUse)},
  { 9, -1, sizeof(::algocomp::SetCateValue)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::algocomp::_SetCateValue_ValsEntry_DoNotUse_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::algocomp::_SetCateValue_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "attrpb/setcate_value.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\032attrpb/setcate_value.proto\022\010algocomp\"k"
      "\n\014SetCateValue\022.\n\004vals\030\001 \003(\0132 .algocomp."
      "SetCateValue.ValsEntry\032+\n\tValsEntry\022\013\n\003k"
      "ey\030\001 \001(\t\022\r\n\005value\030\002 \001(\002:\0028\001B\037\n\010algocompB"
      "\016SetCateValuePbP\001\370\001\001b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 188);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "attrpb/setcate_value.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_attrpb_2fsetcate_5fvalue_2eproto
namespace algocomp {

// ===================================================================

SetCateValue_ValsEntry_DoNotUse::SetCateValue_ValsEntry_DoNotUse() {}
SetCateValue_ValsEntry_DoNotUse::SetCateValue_ValsEntry_DoNotUse(::google::protobuf::Arena* arena) : SuperType(arena) {}
void SetCateValue_ValsEntry_DoNotUse::MergeFrom(const SetCateValue_ValsEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::google::protobuf::Metadata SetCateValue_ValsEntry_DoNotUse::GetMetadata() const {
  ::protobuf_attrpb_2fsetcate_5fvalue_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_attrpb_2fsetcate_5fvalue_2eproto::file_level_metadata[0];
}
void SetCateValue_ValsEntry_DoNotUse::MergeFrom(
    const ::google::protobuf::Message& other) {
  ::google::protobuf::Message::MergeFrom(other);
}


// ===================================================================

void SetCateValue::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SetCateValue::kValsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SetCateValue::SetCateValue()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_attrpb_2fsetcate_5fvalue_2eproto::InitDefaultsSetCateValue();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:algocomp.SetCateValue)
}
SetCateValue::SetCateValue(::google::protobuf::Arena* arena)
  : ::google::protobuf::Message(),
  _internal_metadata_(arena),
  vals_(arena) {
  ::protobuf_attrpb_2fsetcate_5fvalue_2eproto::InitDefaultsSetCateValue();
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:algocomp.SetCateValue)
}
SetCateValue::SetCateValue(const SetCateValue& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  vals_.MergeFrom(from.vals_);
  // @@protoc_insertion_point(copy_constructor:algocomp.SetCateValue)
}

void SetCateValue::SharedCtor() {
  _cached_size_ = 0;
}

SetCateValue::~SetCateValue() {
  // @@protoc_insertion_point(destructor:algocomp.SetCateValue)
  SharedDtor();
}

void SetCateValue::SharedDtor() {
  GOOGLE_DCHECK(GetArenaNoVirtual() == NULL);
}

void SetCateValue::ArenaDtor(void* object) {
  SetCateValue* _this = reinterpret_cast< SetCateValue* >(object);
  (void)_this;
}
void SetCateValue::RegisterArenaDtor(::google::protobuf::Arena* arena) {
}
void SetCateValue::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SetCateValue::descriptor() {
  ::protobuf_attrpb_2fsetcate_5fvalue_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_attrpb_2fsetcate_5fvalue_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SetCateValue& SetCateValue::default_instance() {
  ::protobuf_attrpb_2fsetcate_5fvalue_2eproto::InitDefaultsSetCateValue();
  return *internal_default_instance();
}

SetCateValue* SetCateValue::New(::google::protobuf::Arena* arena) const {
  return ::google::protobuf::Arena::CreateMessage<SetCateValue>(arena);
}

void SetCateValue::Clear() {
// @@protoc_insertion_point(message_clear_start:algocomp.SetCateValue)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  vals_.Clear();
  _internal_metadata_.Clear();
}

bool SetCateValue::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:algocomp.SetCateValue)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // map<string, float> vals = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          SetCateValue_ValsEntry_DoNotUse::Parser< ::google::protobuf::internal::MapField<
              SetCateValue_ValsEntry_DoNotUse,
              ::std::string, float,
              ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
              ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT,
              0 >,
            ::google::protobuf::Map< ::std::string, float > > parser(&vals_);
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
              input, &parser));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            parser.key().data(), static_cast<int>(parser.key().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "algocomp.SetCateValue.ValsEntry.key"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:algocomp.SetCateValue)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:algocomp.SetCateValue)
  return false;
#undef DO_
}

void SetCateValue::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:algocomp.SetCateValue)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // map<string, float> vals = 1;
  if (!this->vals().empty()) {
    typedef ::google::protobuf::Map< ::std::string, float >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::google::protobuf::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), static_cast<int>(p->first.length()),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "algocomp.SetCateValue.ValsEntry.key");
      }
    };

    if (output->IsSerializationDeterministic() &&
        this->vals().size() > 1) {
      ::google::protobuf::scoped_array<SortItem> items(
          new SortItem[this->vals().size()]);
      typedef ::google::protobuf::Map< ::std::string, float >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::std::string, float >::const_iterator
          it = this->vals().begin();
          it != this->vals().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      ::google::protobuf::scoped_ptr<SetCateValue_ValsEntry_DoNotUse> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(vals_.NewEntryWrapper(
            items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
            1, *entry, output);
        if (entry->GetArena() != NULL) {
          entry.release();
        }
        Utf8Check::Check(items[static_cast<ptrdiff_t>(i)]);
      }
    } else {
      ::google::protobuf::scoped_ptr<SetCateValue_ValsEntry_DoNotUse> entry;
      for (::google::protobuf::Map< ::std::string, float >::const_iterator
          it = this->vals().begin();
          it != this->vals().end(); ++it) {
        entry.reset(vals_.NewEntryWrapper(
            it->first, it->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
            1, *entry, output);
        if (entry->GetArena() != NULL) {
          entry.release();
        }
        Utf8Check::Check(&*it);
      }
    }
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:algocomp.SetCateValue)
}

::google::protobuf::uint8* SetCateValue::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:algocomp.SetCateValue)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // map<string, float> vals = 1;
  if (!this->vals().empty()) {
    typedef ::google::protobuf::Map< ::std::string, float >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::google::protobuf::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), static_cast<int>(p->first.length()),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "algocomp.SetCateValue.ValsEntry.key");
      }
    };

    if (deterministic &&
        this->vals().size() > 1) {
      ::google::protobuf::scoped_array<SortItem> items(
          new SortItem[this->vals().size()]);
      typedef ::google::protobuf::Map< ::std::string, float >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::std::string, float >::const_iterator
          it = this->vals().begin();
          it != this->vals().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      ::google::protobuf::scoped_ptr<SetCateValue_ValsEntry_DoNotUse> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(vals_.NewEntryWrapper(
            items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second));
        target = ::google::protobuf::internal::WireFormatLite::
                   InternalWriteMessageNoVirtualToArray(
                       1, *entry, deterministic, target);
;
        if (entry->GetArena() != NULL) {
          entry.release();
        }
        Utf8Check::Check(items[static_cast<ptrdiff_t>(i)]);
      }
    } else {
      ::google::protobuf::scoped_ptr<SetCateValue_ValsEntry_DoNotUse> entry;
      for (::google::protobuf::Map< ::std::string, float >::const_iterator
          it = this->vals().begin();
          it != this->vals().end(); ++it) {
        entry.reset(vals_.NewEntryWrapper(
            it->first, it->second));
        target = ::google::protobuf::internal::WireFormatLite::
                   InternalWriteMessageNoVirtualToArray(
                       1, *entry, deterministic, target);
;
        if (entry->GetArena() != NULL) {
          entry.release();
        }
        Utf8Check::Check(&*it);
      }
    }
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:algocomp.SetCateValue)
  return target;
}

size_t SetCateValue::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:algocomp.SetCateValue)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // map<string, float> vals = 1;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->vals_size());
  {
    ::google::protobuf::scoped_ptr<SetCateValue_ValsEntry_DoNotUse> entry;
    for (::google::protobuf::Map< ::std::string, float >::const_iterator
        it = this->vals().begin();
        it != this->vals().end(); ++it) {
      if (entry.get() != NULL && entry->GetArena() != NULL) {
        entry.release();
      }
      entry.reset(vals_.NewEntryWrapper(it->first, it->second));
      total_size += ::google::protobuf::internal::WireFormatLite::
          MessageSizeNoVirtual(*entry);
    }
    if (entry.get() != NULL && entry->GetArena() != NULL) {
      entry.release();
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SetCateValue::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:algocomp.SetCateValue)
  GOOGLE_DCHECK_NE(&from, this);
  const SetCateValue* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SetCateValue>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:algocomp.SetCateValue)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:algocomp.SetCateValue)
    MergeFrom(*source);
  }
}

void SetCateValue::MergeFrom(const SetCateValue& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:algocomp.SetCateValue)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  vals_.MergeFrom(from.vals_);
}

void SetCateValue::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:algocomp.SetCateValue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SetCateValue::CopyFrom(const SetCateValue& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:algocomp.SetCateValue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SetCateValue::IsInitialized() const {
  return true;
}

void SetCateValue::Swap(SetCateValue* other) {
  if (other == this) return;
  if (GetArenaNoVirtual() == other->GetArenaNoVirtual()) {
    InternalSwap(other);
  } else {
    SetCateValue* temp = New(GetArenaNoVirtual());
    temp->MergeFrom(*other);
    other->CopyFrom(*this);
    InternalSwap(temp);
    if (GetArenaNoVirtual() == NULL) {
      delete temp;
    }
  }
}
void SetCateValue::UnsafeArenaSwap(SetCateValue* other) {
  if (other == this) return;
  GOOGLE_DCHECK(GetArenaNoVirtual() == other->GetArenaNoVirtual());
  InternalSwap(other);
}
void SetCateValue::InternalSwap(SetCateValue* other) {
  using std::swap;
  vals_.Swap(&other->vals_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SetCateValue::GetMetadata() const {
  protobuf_attrpb_2fsetcate_5fvalue_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_attrpb_2fsetcate_5fvalue_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace algocomp

// @@protoc_insertion_point(global_scope)
