// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: attrpb/setcate_value.proto

#ifndef PROTOBUF_attrpb_2fsetcate_5fvalue_2eproto__INCLUDED
#define PROTOBUF_attrpb_2fsetcate_5fvalue_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_attrpb_2fsetcate_5fvalue_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsSetCateValue_ValsEntry_DoNotUseImpl();
void InitDefaultsSetCateValue_ValsEntry_DoNotUse();
void InitDefaultsSetCateValueImpl();
void InitDefaultsSetCateValue();
inline void InitDefaults() {
  InitDefaultsSetCateValue_ValsEntry_DoNotUse();
  InitDefaultsSetCateValue();
}
}  // namespace protobuf_attrpb_2fsetcate_5fvalue_2eproto
namespace algocomp {
class SetCateValue;
class SetCateValueDefaultTypeInternal;
extern SetCateValueDefaultTypeInternal _SetCateValue_default_instance_;
class SetCateValue_ValsEntry_DoNotUse;
class SetCateValue_ValsEntry_DoNotUseDefaultTypeInternal;
extern SetCateValue_ValsEntry_DoNotUseDefaultTypeInternal _SetCateValue_ValsEntry_DoNotUse_default_instance_;
}  // namespace algocomp
namespace algocomp {

// ===================================================================

class SetCateValue_ValsEntry_DoNotUse : public ::google::protobuf::internal::MapEntry<SetCateValue_ValsEntry_DoNotUse, 
    ::std::string, float,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT,
    0 > {
public:
  typedef ::google::protobuf::internal::MapEntry<SetCateValue_ValsEntry_DoNotUse, 
    ::std::string, float,
    ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
    ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT,
    0 > SuperType;
  SetCateValue_ValsEntry_DoNotUse();
  SetCateValue_ValsEntry_DoNotUse(::google::protobuf::Arena* arena);
  void MergeFrom(const SetCateValue_ValsEntry_DoNotUse& other);
  static const SetCateValue_ValsEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const SetCateValue_ValsEntry_DoNotUse*>(&_SetCateValue_ValsEntry_DoNotUse_default_instance_); }
  void MergeFrom(const ::google::protobuf::Message& other) PROTOBUF_FINAL;
  ::google::protobuf::Metadata GetMetadata() const;
};

// -------------------------------------------------------------------

class SetCateValue : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:algocomp.SetCateValue) */ {
 public:
  SetCateValue();
  virtual ~SetCateValue();

  SetCateValue(const SetCateValue& from);

  inline SetCateValue& operator=(const SetCateValue& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SetCateValue(SetCateValue&& from) noexcept
    : SetCateValue() {
    *this = ::std::move(from);
  }

  inline SetCateValue& operator=(SetCateValue&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline ::google::protobuf::Arena* GetArena() const PROTOBUF_FINAL {
    return GetArenaNoVirtual();
  }
  inline void* GetMaybeArenaPointer() const PROTOBUF_FINAL {
    return MaybeArenaPtr();
  }
  static const ::google::protobuf::Descriptor* descriptor();
  static const SetCateValue& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SetCateValue* internal_default_instance() {
    return reinterpret_cast<const SetCateValue*>(
               &_SetCateValue_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void UnsafeArenaSwap(SetCateValue* other);
  void Swap(SetCateValue* other);
  friend void swap(SetCateValue& a, SetCateValue& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SetCateValue* New() const PROTOBUF_FINAL { return New(NULL); }

  SetCateValue* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SetCateValue& from);
  void MergeFrom(const SetCateValue& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SetCateValue* other);
  protected:
  explicit SetCateValue(::google::protobuf::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::google::protobuf::Arena* arena);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<string, float> vals = 1;
  int vals_size() const;
  void clear_vals();
  static const int kValsFieldNumber = 1;
  const ::google::protobuf::Map< ::std::string, float >&
      vals() const;
  ::google::protobuf::Map< ::std::string, float >*
      mutable_vals();

  // @@protoc_insertion_point(class_scope:algocomp.SetCateValue)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::google::protobuf::internal::MapField<
      SetCateValue_ValsEntry_DoNotUse,
      ::std::string, float,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT,
      0 > vals_;
  mutable int _cached_size_;
  friend struct ::protobuf_attrpb_2fsetcate_5fvalue_2eproto::TableStruct;
  friend void ::protobuf_attrpb_2fsetcate_5fvalue_2eproto::InitDefaultsSetCateValueImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// SetCateValue

// map<string, float> vals = 1;
inline int SetCateValue::vals_size() const {
  return vals_.size();
}
inline void SetCateValue::clear_vals() {
  vals_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, float >&
SetCateValue::vals() const {
  // @@protoc_insertion_point(field_map:algocomp.SetCateValue.vals)
  return vals_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, float >*
SetCateValue::mutable_vals() {
  // @@protoc_insertion_point(field_mutable_map:algocomp.SetCateValue.vals)
  return vals_.MutableMap();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace algocomp

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_attrpb_2fsetcate_5fvalue_2eproto__INCLUDED
