// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: featpb/feature_bunch.proto

#include "featpb/feature_bunch.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace algocomp {
class FeatureBunch_DiscFeatsEntry_DoNotUseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<FeatureBunch_DiscFeatsEntry_DoNotUse>
      _instance;
} _FeatureBunch_DiscFeatsEntry_DoNotUse_default_instance_;
class FeatureBunch_ContFeatsEntry_DoNotUseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<FeatureBunch_ContFeatsEntry_DoNotUse>
      _instance;
} _FeatureBunch_ContFeatsEntry_DoNotUse_default_instance_;
class FeatureBunchDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<FeatureBunch>
      _instance;
} _FeatureBunch_default_instance_;
}  // namespace algocomp
namespace protobuf_featpb_2ffeature_5fbunch_2eproto {
void InitDefaultsFeatureBunch_DiscFeatsEntry_DoNotUseImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_featpb_2fdisc_5ffeat_5fgrp_2eproto::InitDefaultsDiscFeatGrp();
  {
    void* ptr = &::algocomp::_FeatureBunch_DiscFeatsEntry_DoNotUse_default_instance_;
    new (ptr) ::algocomp::FeatureBunch_DiscFeatsEntry_DoNotUse();
  }
  ::algocomp::FeatureBunch_DiscFeatsEntry_DoNotUse::InitAsDefaultInstance();
}

void InitDefaultsFeatureBunch_DiscFeatsEntry_DoNotUse() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsFeatureBunch_DiscFeatsEntry_DoNotUseImpl);
}

void InitDefaultsFeatureBunch_ContFeatsEntry_DoNotUseImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_featpb_2fcont_5ffeat_5fgrp_2eproto::InitDefaultsContFeatGrp();
  {
    void* ptr = &::algocomp::_FeatureBunch_ContFeatsEntry_DoNotUse_default_instance_;
    new (ptr) ::algocomp::FeatureBunch_ContFeatsEntry_DoNotUse();
  }
  ::algocomp::FeatureBunch_ContFeatsEntry_DoNotUse::InitAsDefaultInstance();
}

void InitDefaultsFeatureBunch_ContFeatsEntry_DoNotUse() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsFeatureBunch_ContFeatsEntry_DoNotUseImpl);
}

void InitDefaultsFeatureBunchImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_featpb_2ffeature_5fbunch_2eproto::InitDefaultsFeatureBunch_DiscFeatsEntry_DoNotUse();
  protobuf_featpb_2ffeature_5fbunch_2eproto::InitDefaultsFeatureBunch_ContFeatsEntry_DoNotUse();
  {
    void* ptr = &::algocomp::_FeatureBunch_default_instance_;
    new (ptr) ::algocomp::FeatureBunch();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::algocomp::FeatureBunch::InitAsDefaultInstance();
}

void InitDefaultsFeatureBunch() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsFeatureBunchImpl);
}

::google::protobuf::Metadata file_level_metadata[3];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::algocomp::FeatureBunch_DiscFeatsEntry_DoNotUse, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::algocomp::FeatureBunch_DiscFeatsEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::algocomp::FeatureBunch_DiscFeatsEntry_DoNotUse, key_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::algocomp::FeatureBunch_DiscFeatsEntry_DoNotUse, value_),
  0,
  1,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::algocomp::FeatureBunch_ContFeatsEntry_DoNotUse, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::algocomp::FeatureBunch_ContFeatsEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::algocomp::FeatureBunch_ContFeatsEntry_DoNotUse, key_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::algocomp::FeatureBunch_ContFeatsEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::algocomp::FeatureBunch, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::algocomp::FeatureBunch, disc_feats_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::algocomp::FeatureBunch, cont_feats_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, sizeof(::algocomp::FeatureBunch_DiscFeatsEntry_DoNotUse)},
  { 9, 16, sizeof(::algocomp::FeatureBunch_ContFeatsEntry_DoNotUse)},
  { 18, -1, sizeof(::algocomp::FeatureBunch)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::algocomp::_FeatureBunch_DiscFeatsEntry_DoNotUse_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::algocomp::_FeatureBunch_ContFeatsEntry_DoNotUse_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::algocomp::_FeatureBunch_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "featpb/feature_bunch.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\032featpb/feature_bunch.proto\022\010algocomp\032\032"
      "featpb/cont_feat_grp.proto\032\032featpb/disc_"
      "feat_grp.proto\"\226\002\n\014FeatureBunch\0229\n\ndisc_"
      "feats\030\001 \003(\0132%.algocomp.FeatureBunch.Disc"
      "FeatsEntry\0229\n\ncont_feats\030\002 \003(\0132%.algocom"
      "p.FeatureBunch.ContFeatsEntry\032G\n\016DiscFea"
      "tsEntry\022\013\n\003key\030\001 \001(\t\022$\n\005value\030\002 \001(\0132\025.al"
      "gocomp.DiscFeatGrp:\0028\001\032G\n\016ContFeatsEntry"
      "\022\013\n\003key\030\001 \001(\t\022$\n\005value\030\002 \001(\0132\025.algocomp."
      "ContFeatGrp:\0028\001B\037\n\010algocompB\016FeatureBunc"
      "hPbP\001\370\001\001b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 416);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "featpb/feature_bunch.proto", &protobuf_RegisterTypes);
  ::protobuf_featpb_2fcont_5ffeat_5fgrp_2eproto::AddDescriptors();
  ::protobuf_featpb_2fdisc_5ffeat_5fgrp_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_featpb_2ffeature_5fbunch_2eproto
namespace algocomp {

// ===================================================================

FeatureBunch_DiscFeatsEntry_DoNotUse::FeatureBunch_DiscFeatsEntry_DoNotUse() {}
FeatureBunch_DiscFeatsEntry_DoNotUse::FeatureBunch_DiscFeatsEntry_DoNotUse(::google::protobuf::Arena* arena) : SuperType(arena) {}
void FeatureBunch_DiscFeatsEntry_DoNotUse::MergeFrom(const FeatureBunch_DiscFeatsEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::google::protobuf::Metadata FeatureBunch_DiscFeatsEntry_DoNotUse::GetMetadata() const {
  ::protobuf_featpb_2ffeature_5fbunch_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_featpb_2ffeature_5fbunch_2eproto::file_level_metadata[0];
}
void FeatureBunch_DiscFeatsEntry_DoNotUse::MergeFrom(
    const ::google::protobuf::Message& other) {
  ::google::protobuf::Message::MergeFrom(other);
}


// ===================================================================

FeatureBunch_ContFeatsEntry_DoNotUse::FeatureBunch_ContFeatsEntry_DoNotUse() {}
FeatureBunch_ContFeatsEntry_DoNotUse::FeatureBunch_ContFeatsEntry_DoNotUse(::google::protobuf::Arena* arena) : SuperType(arena) {}
void FeatureBunch_ContFeatsEntry_DoNotUse::MergeFrom(const FeatureBunch_ContFeatsEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::google::protobuf::Metadata FeatureBunch_ContFeatsEntry_DoNotUse::GetMetadata() const {
  ::protobuf_featpb_2ffeature_5fbunch_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_featpb_2ffeature_5fbunch_2eproto::file_level_metadata[1];
}
void FeatureBunch_ContFeatsEntry_DoNotUse::MergeFrom(
    const ::google::protobuf::Message& other) {
  ::google::protobuf::Message::MergeFrom(other);
}


// ===================================================================

void FeatureBunch::InitAsDefaultInstance() {
}
void FeatureBunch::clear_disc_feats() {
  disc_feats_.Clear();
}
void FeatureBunch::clear_cont_feats() {
  cont_feats_.Clear();
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int FeatureBunch::kDiscFeatsFieldNumber;
const int FeatureBunch::kContFeatsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

FeatureBunch::FeatureBunch()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_featpb_2ffeature_5fbunch_2eproto::InitDefaultsFeatureBunch();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:algocomp.FeatureBunch)
}
FeatureBunch::FeatureBunch(::google::protobuf::Arena* arena)
  : ::google::protobuf::Message(),
  _internal_metadata_(arena),
  disc_feats_(arena),
  cont_feats_(arena) {
  ::protobuf_featpb_2ffeature_5fbunch_2eproto::InitDefaultsFeatureBunch();
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:algocomp.FeatureBunch)
}
FeatureBunch::FeatureBunch(const FeatureBunch& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  disc_feats_.MergeFrom(from.disc_feats_);
  cont_feats_.MergeFrom(from.cont_feats_);
  // @@protoc_insertion_point(copy_constructor:algocomp.FeatureBunch)
}

void FeatureBunch::SharedCtor() {
  _cached_size_ = 0;
}

FeatureBunch::~FeatureBunch() {
  // @@protoc_insertion_point(destructor:algocomp.FeatureBunch)
  SharedDtor();
}

void FeatureBunch::SharedDtor() {
  GOOGLE_DCHECK(GetArenaNoVirtual() == NULL);
}

void FeatureBunch::ArenaDtor(void* object) {
  FeatureBunch* _this = reinterpret_cast< FeatureBunch* >(object);
  (void)_this;
}
void FeatureBunch::RegisterArenaDtor(::google::protobuf::Arena* arena) {
}
void FeatureBunch::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* FeatureBunch::descriptor() {
  ::protobuf_featpb_2ffeature_5fbunch_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_featpb_2ffeature_5fbunch_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const FeatureBunch& FeatureBunch::default_instance() {
  ::protobuf_featpb_2ffeature_5fbunch_2eproto::InitDefaultsFeatureBunch();
  return *internal_default_instance();
}

FeatureBunch* FeatureBunch::New(::google::protobuf::Arena* arena) const {
  return ::google::protobuf::Arena::CreateMessage<FeatureBunch>(arena);
}

void FeatureBunch::Clear() {
// @@protoc_insertion_point(message_clear_start:algocomp.FeatureBunch)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  disc_feats_.Clear();
  cont_feats_.Clear();
  _internal_metadata_.Clear();
}

bool FeatureBunch::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:algocomp.FeatureBunch)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // map<string, .algocomp.DiscFeatGrp> disc_feats = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          FeatureBunch_DiscFeatsEntry_DoNotUse::Parser< ::google::protobuf::internal::MapField<
              FeatureBunch_DiscFeatsEntry_DoNotUse,
              ::std::string, ::algocomp::DiscFeatGrp,
              ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
              ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
              0 >,
            ::google::protobuf::Map< ::std::string, ::algocomp::DiscFeatGrp > > parser(&disc_feats_);
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
              input, &parser));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            parser.key().data(), static_cast<int>(parser.key().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "algocomp.FeatureBunch.DiscFeatsEntry.key"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // map<string, .algocomp.ContFeatGrp> cont_feats = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          FeatureBunch_ContFeatsEntry_DoNotUse::Parser< ::google::protobuf::internal::MapField<
              FeatureBunch_ContFeatsEntry_DoNotUse,
              ::std::string, ::algocomp::ContFeatGrp,
              ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
              ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
              0 >,
            ::google::protobuf::Map< ::std::string, ::algocomp::ContFeatGrp > > parser(&cont_feats_);
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
              input, &parser));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            parser.key().data(), static_cast<int>(parser.key().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "algocomp.FeatureBunch.ContFeatsEntry.key"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:algocomp.FeatureBunch)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:algocomp.FeatureBunch)
  return false;
#undef DO_
}

void FeatureBunch::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:algocomp.FeatureBunch)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // map<string, .algocomp.DiscFeatGrp> disc_feats = 1;
  if (!this->disc_feats().empty()) {
    typedef ::google::protobuf::Map< ::std::string, ::algocomp::DiscFeatGrp >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::google::protobuf::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), static_cast<int>(p->first.length()),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "algocomp.FeatureBunch.DiscFeatsEntry.key");
      }
    };

    if (output->IsSerializationDeterministic() &&
        this->disc_feats().size() > 1) {
      ::google::protobuf::scoped_array<SortItem> items(
          new SortItem[this->disc_feats().size()]);
      typedef ::google::protobuf::Map< ::std::string, ::algocomp::DiscFeatGrp >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::std::string, ::algocomp::DiscFeatGrp >::const_iterator
          it = this->disc_feats().begin();
          it != this->disc_feats().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      ::google::protobuf::scoped_ptr<FeatureBunch_DiscFeatsEntry_DoNotUse> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(disc_feats_.NewEntryWrapper(
            items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
            1, *entry, output);
        if (entry->GetArena() != NULL) {
          entry.release();
        }
        Utf8Check::Check(items[static_cast<ptrdiff_t>(i)]);
      }
    } else {
      ::google::protobuf::scoped_ptr<FeatureBunch_DiscFeatsEntry_DoNotUse> entry;
      for (::google::protobuf::Map< ::std::string, ::algocomp::DiscFeatGrp >::const_iterator
          it = this->disc_feats().begin();
          it != this->disc_feats().end(); ++it) {
        entry.reset(disc_feats_.NewEntryWrapper(
            it->first, it->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
            1, *entry, output);
        if (entry->GetArena() != NULL) {
          entry.release();
        }
        Utf8Check::Check(&*it);
      }
    }
  }

  // map<string, .algocomp.ContFeatGrp> cont_feats = 2;
  if (!this->cont_feats().empty()) {
    typedef ::google::protobuf::Map< ::std::string, ::algocomp::ContFeatGrp >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::google::protobuf::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), static_cast<int>(p->first.length()),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "algocomp.FeatureBunch.ContFeatsEntry.key");
      }
    };

    if (output->IsSerializationDeterministic() &&
        this->cont_feats().size() > 1) {
      ::google::protobuf::scoped_array<SortItem> items(
          new SortItem[this->cont_feats().size()]);
      typedef ::google::protobuf::Map< ::std::string, ::algocomp::ContFeatGrp >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::std::string, ::algocomp::ContFeatGrp >::const_iterator
          it = this->cont_feats().begin();
          it != this->cont_feats().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      ::google::protobuf::scoped_ptr<FeatureBunch_ContFeatsEntry_DoNotUse> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(cont_feats_.NewEntryWrapper(
            items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
            2, *entry, output);
        if (entry->GetArena() != NULL) {
          entry.release();
        }
        Utf8Check::Check(items[static_cast<ptrdiff_t>(i)]);
      }
    } else {
      ::google::protobuf::scoped_ptr<FeatureBunch_ContFeatsEntry_DoNotUse> entry;
      for (::google::protobuf::Map< ::std::string, ::algocomp::ContFeatGrp >::const_iterator
          it = this->cont_feats().begin();
          it != this->cont_feats().end(); ++it) {
        entry.reset(cont_feats_.NewEntryWrapper(
            it->first, it->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
            2, *entry, output);
        if (entry->GetArena() != NULL) {
          entry.release();
        }
        Utf8Check::Check(&*it);
      }
    }
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:algocomp.FeatureBunch)
}

::google::protobuf::uint8* FeatureBunch::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:algocomp.FeatureBunch)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // map<string, .algocomp.DiscFeatGrp> disc_feats = 1;
  if (!this->disc_feats().empty()) {
    typedef ::google::protobuf::Map< ::std::string, ::algocomp::DiscFeatGrp >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::google::protobuf::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), static_cast<int>(p->first.length()),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "algocomp.FeatureBunch.DiscFeatsEntry.key");
      }
    };

    if (deterministic &&
        this->disc_feats().size() > 1) {
      ::google::protobuf::scoped_array<SortItem> items(
          new SortItem[this->disc_feats().size()]);
      typedef ::google::protobuf::Map< ::std::string, ::algocomp::DiscFeatGrp >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::std::string, ::algocomp::DiscFeatGrp >::const_iterator
          it = this->disc_feats().begin();
          it != this->disc_feats().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      ::google::protobuf::scoped_ptr<FeatureBunch_DiscFeatsEntry_DoNotUse> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(disc_feats_.NewEntryWrapper(
            items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second));
        target = ::google::protobuf::internal::WireFormatLite::
                   InternalWriteMessageNoVirtualToArray(
                       1, *entry, deterministic, target);
;
        if (entry->GetArena() != NULL) {
          entry.release();
        }
        Utf8Check::Check(items[static_cast<ptrdiff_t>(i)]);
      }
    } else {
      ::google::protobuf::scoped_ptr<FeatureBunch_DiscFeatsEntry_DoNotUse> entry;
      for (::google::protobuf::Map< ::std::string, ::algocomp::DiscFeatGrp >::const_iterator
          it = this->disc_feats().begin();
          it != this->disc_feats().end(); ++it) {
        entry.reset(disc_feats_.NewEntryWrapper(
            it->first, it->second));
        target = ::google::protobuf::internal::WireFormatLite::
                   InternalWriteMessageNoVirtualToArray(
                       1, *entry, deterministic, target);
;
        if (entry->GetArena() != NULL) {
          entry.release();
        }
        Utf8Check::Check(&*it);
      }
    }
  }

  // map<string, .algocomp.ContFeatGrp> cont_feats = 2;
  if (!this->cont_feats().empty()) {
    typedef ::google::protobuf::Map< ::std::string, ::algocomp::ContFeatGrp >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::google::protobuf::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), static_cast<int>(p->first.length()),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "algocomp.FeatureBunch.ContFeatsEntry.key");
      }
    };

    if (deterministic &&
        this->cont_feats().size() > 1) {
      ::google::protobuf::scoped_array<SortItem> items(
          new SortItem[this->cont_feats().size()]);
      typedef ::google::protobuf::Map< ::std::string, ::algocomp::ContFeatGrp >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::std::string, ::algocomp::ContFeatGrp >::const_iterator
          it = this->cont_feats().begin();
          it != this->cont_feats().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      ::google::protobuf::scoped_ptr<FeatureBunch_ContFeatsEntry_DoNotUse> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(cont_feats_.NewEntryWrapper(
            items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second));
        target = ::google::protobuf::internal::WireFormatLite::
                   InternalWriteMessageNoVirtualToArray(
                       2, *entry, deterministic, target);
;
        if (entry->GetArena() != NULL) {
          entry.release();
        }
        Utf8Check::Check(items[static_cast<ptrdiff_t>(i)]);
      }
    } else {
      ::google::protobuf::scoped_ptr<FeatureBunch_ContFeatsEntry_DoNotUse> entry;
      for (::google::protobuf::Map< ::std::string, ::algocomp::ContFeatGrp >::const_iterator
          it = this->cont_feats().begin();
          it != this->cont_feats().end(); ++it) {
        entry.reset(cont_feats_.NewEntryWrapper(
            it->first, it->second));
        target = ::google::protobuf::internal::WireFormatLite::
                   InternalWriteMessageNoVirtualToArray(
                       2, *entry, deterministic, target);
;
        if (entry->GetArena() != NULL) {
          entry.release();
        }
        Utf8Check::Check(&*it);
      }
    }
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:algocomp.FeatureBunch)
  return target;
}

size_t FeatureBunch::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:algocomp.FeatureBunch)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // map<string, .algocomp.DiscFeatGrp> disc_feats = 1;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->disc_feats_size());
  {
    ::google::protobuf::scoped_ptr<FeatureBunch_DiscFeatsEntry_DoNotUse> entry;
    for (::google::protobuf::Map< ::std::string, ::algocomp::DiscFeatGrp >::const_iterator
        it = this->disc_feats().begin();
        it != this->disc_feats().end(); ++it) {
      if (entry.get() != NULL && entry->GetArena() != NULL) {
        entry.release();
      }
      entry.reset(disc_feats_.NewEntryWrapper(it->first, it->second));
      total_size += ::google::protobuf::internal::WireFormatLite::
          MessageSizeNoVirtual(*entry);
    }
    if (entry.get() != NULL && entry->GetArena() != NULL) {
      entry.release();
    }
  }

  // map<string, .algocomp.ContFeatGrp> cont_feats = 2;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->cont_feats_size());
  {
    ::google::protobuf::scoped_ptr<FeatureBunch_ContFeatsEntry_DoNotUse> entry;
    for (::google::protobuf::Map< ::std::string, ::algocomp::ContFeatGrp >::const_iterator
        it = this->cont_feats().begin();
        it != this->cont_feats().end(); ++it) {
      if (entry.get() != NULL && entry->GetArena() != NULL) {
        entry.release();
      }
      entry.reset(cont_feats_.NewEntryWrapper(it->first, it->second));
      total_size += ::google::protobuf::internal::WireFormatLite::
          MessageSizeNoVirtual(*entry);
    }
    if (entry.get() != NULL && entry->GetArena() != NULL) {
      entry.release();
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void FeatureBunch::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:algocomp.FeatureBunch)
  GOOGLE_DCHECK_NE(&from, this);
  const FeatureBunch* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const FeatureBunch>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:algocomp.FeatureBunch)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:algocomp.FeatureBunch)
    MergeFrom(*source);
  }
}

void FeatureBunch::MergeFrom(const FeatureBunch& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:algocomp.FeatureBunch)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  disc_feats_.MergeFrom(from.disc_feats_);
  cont_feats_.MergeFrom(from.cont_feats_);
}

void FeatureBunch::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:algocomp.FeatureBunch)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FeatureBunch::CopyFrom(const FeatureBunch& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:algocomp.FeatureBunch)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FeatureBunch::IsInitialized() const {
  return true;
}

void FeatureBunch::Swap(FeatureBunch* other) {
  if (other == this) return;
  if (GetArenaNoVirtual() == other->GetArenaNoVirtual()) {
    InternalSwap(other);
  } else {
    FeatureBunch* temp = New(GetArenaNoVirtual());
    temp->MergeFrom(*other);
    other->CopyFrom(*this);
    InternalSwap(temp);
    if (GetArenaNoVirtual() == NULL) {
      delete temp;
    }
  }
}
void FeatureBunch::UnsafeArenaSwap(FeatureBunch* other) {
  if (other == this) return;
  GOOGLE_DCHECK(GetArenaNoVirtual() == other->GetArenaNoVirtual());
  InternalSwap(other);
}
void FeatureBunch::InternalSwap(FeatureBunch* other) {
  using std::swap;
  disc_feats_.Swap(&other->disc_feats_);
  cont_feats_.Swap(&other->cont_feats_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata FeatureBunch::GetMetadata() const {
  protobuf_featpb_2ffeature_5fbunch_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_featpb_2ffeature_5fbunch_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace algocomp

// @@protoc_insertion_point(global_scope)
